In [2]:
######################## 机器学习对数几率回归类 ##############################
# Author: 杨玉奇
# email: yangyuqi@sina.com
# url: https://github.com/jerryyyq/tf_algorithm_example
# copyright yangyuqi
# 著作权归作者 杨玉奇 所有。商业转载请联系作者获得授权，非商业转载请注明出处。
# date: 2017-09-19
###################################################################

from ML_Model import ML_Model
import tensorflow as tf
    
class ML_Softmax_Regression( ML_Model ):
    def __init__(self):
        ML_Model.__init__(self)

        self.__W = tf.Variable(tf.zeros([4, 3]), name = 'weights')
        self.__b = tf.Variable(tf.zeros([3]), name = 'bias')
    
        
    def combine_inputs(self, features):
        return tf.matmul(features, self.__W) + self.__b
    
    def inference(self, features):
        return tf.nn.softmax( self.combine_inputs(features) )
    
    def loss(self, features, label):
        label_predicted = self.combine_inputs(features)
        return tf.reduce_mean( tf.nn.sparse_softmax_cross_entropy_with_logits(label_predicted, label) )
    
    
    def inputs(self, file_name = [], batch_size = 10):
        sepal_length, sepal_width, setal_length, setal_width, label = \
        self._read_csv(batch_size, file_name, [[0.0], [0.0], [0.0], [0.0], ['']])

        # return passenger_id, survived
        label_number = tf.to_int32(tf.argmax(tf.to_int32(tf.pack([
            tf.equal(label, ['Iris-setosa']),
            tf.equal(label, ['Iris-versicolor']),
            tf.equal(label, ['Iris-virginica'])
        ])), 0))
        
        features = tf.transpose(tf.pack([sepal_length, sepal_width, setal_length, setal_width]))

        return features, label_number 
        
        
    def train(self, loss):    
        learning_rate = 0.01
        return tf.train.GradientDescentOptimizer( learning_rate ).minimize( loss )

    
    def evaluate(self, test_features, test_label):
        self._echo_tensor(self.__W, 'At evaluate, the __W')
        self._echo_tensor(self.__b, 'At evaluate, the __b')
        self._echo_tensor(test_features, 'At evaluate, test_features')
        self._echo_tensor(test_label, 'At evaluate, test_label')
        
        label_predicted = tf.cast( tf.arg_max(self.inference(test_features), 1), tf.int32 )
        
        return tf.reduce_mean(tf.cast(tf.equal(label_predicted, test_label), tf.float32))

    
if __name__ == '__main__':
    one_ml = ML_Softmax_Regression()
    # data from: https://archive.ics.uci.edu/ml/datasets/Iris
    one_ml.do_train( 10, ['iris.csv'] )

    one_ml.do_evaluate( ['iris.csv'] )

    

-------------- do_train: start -----------------
file_path =  ['/home/yangyuqi/work/tf_algorithm_example/iris.csv'] 

Tensor("ReaderRead_2:0", shape=(), dtype=string) Tensor("ReaderRead_2:1", shape=(), dtype=string)
features_0 tensor.shape = [10  4], tensor = [[ 4.69999981  3.20000005  1.60000002  0.2       ]
 [ 5.19999981  4.0999999   1.5         0.1       ]
 [ 5.5         4.19999981  1.39999998  0.2       ]
 [ 5.19999981  3.5         1.5         0.2       ]
 [ 4.80000019  3.0999999   1.60000002  0.2       ]
 [ 4.5999999   3.5999999   1.          0.2       ]
 [ 4.80000019  3.4000001   1.89999998  0.2       ]
 [ 5.          3.4000001   1.60000002  0.40000001]
 [ 5.0999999   3.5         1.39999998  0.30000001]
 [ 5.4000001   3.4000001   1.5         0.40000001]]

label_0 tensor.shape = [10], tensor = [0 0 0 1 1 1 1 0 1 1]

step_0 loss:  tensor.shape = [], tensor = 1.2348291873931885

training end. step_9 final loss:  tensor.shape = [], tensor = 1.3672845363616943

save_path is:  /tmp/ML_

NotFoundError: FetchOutputs node Shape_324:0: not found

In [ ]:
# 中间计算数据样例展示
import tensorflow as tf

f = [[5.5, 4.19999981, 1.39999998, 0.2],
     [5.0999999, 3.4000001, 1.5, 0.2],
     [5.69999981, 3.79999995, 1.70000005, 0.30000001]]

label = [['Iris-setosa']
tf.pack([
            tf.equal(label, ['Iris-setosa']),
            tf.equal(label, ['Iris-versicolor']),
            tf.equal(label, ['Iris-virginica'])
        ]))